name: mobile_bro_food_admin_panel
description: This Admin Panel


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_html: any
  url_strategy: ^0.2.0
  universal_html: ^2.0.4


  flutter_secure_storage: ^6.0.0
  equatable: any
  firebase_core: any
  firebase_auth: any
  flutter_provider: any
  provider: any
  dio: any
  responsive_framework: ^0.2.0
  image_picker_web: ^2.1.1
  firebase_storage: any
  graphql_flutter: any

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/logo/
  #   - images/a_dot_ham.jpeg
