// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNg6D_8a4o6VdtcwtJZGUBaZ1SBA7EA-E',
    appId: '1:193273115262:web:93392ceb7cd52d70315e2f',
    messagingSenderId: '193273115262',
    projectId: 'mycar-2ab4d',
    authDomain: 'mycar-2ab4d.firebaseapp.com',
    databaseURL: 'https://mycar-2ab4d-default-rtdb.firebaseio.com',
    storageBucket: 'mycar-2ab4d.appspot.com',
    measurementId: 'G-NK7CZ09JL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtA5WIz_6BwhoQCHXHaG0TtjHOew1z-Ow',
    appId: '1:193273115262:android:024a9a1f728457e4315e2f',
    messagingSenderId: '193273115262',
    projectId: 'mycar-2ab4d',
    databaseURL: 'https://mycar-2ab4d-default-rtdb.firebaseio.com',
    storageBucket: 'mycar-2ab4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvpy_Zt79MRyFti263C6N-VIHAo3s1qrI',
    appId: '1:193273115262:ios:bae6f63367dba6b0315e2f',
    messagingSenderId: '193273115262',
    projectId: 'mycar-2ab4d',
    databaseURL: 'https://mycar-2ab4d-default-rtdb.firebaseio.com',
    storageBucket: 'mycar-2ab4d.appspot.com',
    iosClientId: '193273115262-flpog4jmpsnte6jiqlkempifnkbs5du0.apps.googleusercontent.com',
    iosBundleId: 'com.pdp.mobileBroFoodAdminPanel',
  );
}
